all:
  hosts:
    node1:
      ansible_host: node1
      ip: 129.59.104.15
      access_ip: 129.59.104.15
    node2:
      ansible_host: node2
      ip: 129.59.104.57
      access_ip: 129.59.104.57
    node3:
      ansible_host: node3
      ip: 129.59.104.59
      access_ip: 129.59.104.59
    node4:
      ansible_host: node4
      ip: 129.59.104.123
      access_ip: 129.59.104.123
    node5:
      ansible_host: node5
      ip: 129.59.104.178
      access_ip: 129.59.104.178
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
